# Generated by Django 4.1.7 on 2023-03-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpa_crudedjango_system', '0002_alter_people_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='Name',
            new_name='name',
        ),
    ]
